features:
  - treatAsYear
  - avgIntXing
  - eventClean
  - isBadTile
  - jet_isBadTight
  - IsMETTrigPassed
  - LeptonVeto
  - JetTileVeto
  - TauTileVeto
  - JetTileVetoLBA52
  - TauTileVetoLBA52
  - CosmicMuonVeto
  - tau_n
  - tau_pt
  - tau_eta
  - tau_phi
  - tau_m
  - tau_charge
  - tau_ntracks
  - tau_nIsolatedTracks
  - tau_nAllTracks
  - tau_vertex_index
  - tau_vertex_z
  - tau_width
  - tau_trkwidth_PV
  - tau_trkwidth_TV
  - tau_trkwidth_PV_1k
  - tau_trkwidth_TV_1k
  - tau_jetpt
  - tau_RNNJetScoreSigTrans
  - tau_JetRNNLoose
  - tau_JetRNNMedium
  - tau_JetRNNTight
  - tau_RNNEleScoreSigTrans
  - tau_TileStatus
  - tau_LBA52status
  - tau_delPhiMet
  - tau_mtMet
  - tau_nPi0
  - tau_PantauDecayMode
  - tau_NNDecayMode
  - tau_NNDecayModeProb_1p0n
  - tau_NNDecayModeProb_1p1n
  - tau_NNDecayModeProb_1pXn
  - tau_NNDecayModeProb_3p0n
  - tau_NNDecayModeProb_3pXn
  - jet_n
  - jet_n_btag
  - jet_pt
  - jet_eta
  - jet_phi
  - jet_rapidity
  - jet_m
  - jet_mtMet
  - jet_DL1pb
  - jet_DL1pc
  - jet_DL1pu
  - jet_isBjet
  - jet_jvt
  - jet_delPhiMet
  - jet_width
  - jet_TileStatus
  - jet_LBA52status
  - jet_eleMatch
  - jet_muMatch
  - jet_isBjetMatched
  - jet_timing
  - ele_n
  - ele_pt
  - ele_eta
  - ele_phi
  - ele_m
  - ele_mtMet
  - ele_charge
  - ele_trigmatched
  - mu_n
  - mu_pt
  - mu_eta
  - mu_phi
  - mu_m
  - mu_mtMet
  - mu_charge
  - mu_author
  - mu_muonType
  - mu_isCosmic
  - mu_trigmatched
  - sumMT
  - sumMTJet
  - sumMTTauJet
  - Mt2
  - Mt2_taumu
  - Mt2_tauel
  - Mtaumu
  - Mtauel
  - met
  - met_phi
  - metNoMuon
  - metNoMuon_phi
  - METSig
  - METSigSoftSub
  - METoverPtMean
  - METoverPtMean12
  - meff
  - ht
  - mcEventWeight
  - pileupweight
  - beamSpotWeight
  - ele_weight
  - mu_weight
  - jvt_weight
  - bjet_weight
  - jet_btag_weight
  - Bjet_PileupWeight
  - lumiweight
  - tau_isTruthMatchedTau
