features:
  - SampleID
  - eventClean
  - isBadTile
  - jet_isBadTight
  - IsMETTrigPassed
  - tau_n
  - tau_pt
  - tau_eta
  - tau_phi
  - tau_charge
  - tau_JetRNNMedium
  - tau_delPhiMet
  - tau_mtMet
  - jet_n
  - jet_n_btag
  - jet_pt
  - jet_eta
  - jet_phi
  - jet_delPhiMet
  - mu_n
  - mu_mtMet
  - sumMT
  - Mt2
  - Mt2_taumu
  - Mtaumu
  - met
  - met_phi
  - meff
  - ht
  - mcEventWeight
  - pileupweight
  - beamSpotWeight
  - ele_weight
  - mu_weight
  - jvt_weight
  - bjet_weight
  - jet_btag_weight
  - lumiweight
  - tau_isTruthMatchedTau
  - METSig_seed
  - METSigPow3_seed
  - METSigSoftSub_seed
  - METoverPtMean_seed
  - METoverPtMean12_seed
  - HLT_jX_prescale
  - tau_truthType
  - LeptonVeto
