name: "pytorch_dnn"

hidden_sizes: [128, 128, 128, 128, 128]
activation: "ReLU"
dropout: 0.2

n_epochs: 1000
batch_size: 4096

learning_rate: 0.001
weight_decay: 1e-5

scheduler:
  factor: 0.5
  patience: 10

amp: true
