name: "xgboost"

booster: "gbtree"
n_estimators: 10000
learning_rate: 0.032
max_depth: 8
min_child_weight: 4
gamma: 0.0016
subsample: 0.84
colsample_bytree: 0.96
reg_alpha: 0.00024
reg_lambda: 0.0089
max_delta_step: 0

tree_method: "hist"
device: "cuda"
seed: 1
verbosity: 0
