defaults:
  - _self_
  - data: default
  - model: xgboost
  - pipeline: default
  - features: default
  - paths: default
  - merge: default
  - run@analysis: run2
  - regions@analysis: preselection_ch1
  - samples@samples.background: background
  - samples@samples.signal: signal
  - samples@samples.data: data
  - ml_regions: default
  - tuning: default
  - override hydra/job_logging: default

experiment_name: "tau-supersymmetry-baseline"
seed: 1
